export const textT = {
  days: {
    be: [
      "Панядзелак",
      "Аўторак",
      "Серада",
      "Чацвер",
      "Пятніца",
      "Субота",
      "Нядзеля",
    ],
    ru: [
      "Понедельник",
      "Вторник",
      "Среда",
      "Четверг",
      "Пятница",
      "Суббота",
      "Воскресенье",
    ],
    en: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
  },
  months: {
    be: [
      "Студзеня",
      "Лютага",
      "Сакавіка",
      "Красавіка",
      "Мая",
      "Чэрвеня",
      "Ліпеня",
      "Жнівеня",
      "Верасня",
      "Кастрычніка",
      "Лістапада",
      "Снежня",
    ],
    ru: [
      "Января",
      "Февраля",
      "Марта",
      "Апреля",
      "Мая",
      "Июня",
      "Июля",
      "Августа",
      "Сентября",
      "Октября",
      "Ноября",
      "Декабря",
    ],
    en: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ],
  },
  greetings: {
    be: {
      morning: "Добрай раніцы",
      afternoon: "Добры дзень",
      evening: "Добры вечар",
      night: "Дабранач",
    },
    ru: {
      morning: "Доброе утро",
      afternoon: "Добрый день",
      evening: "Добрый вечер",
      night: "Доброй ночи",
    },
    en: {
      morning: "Good morning",
      afternoon: "Good afternoon",
      evening: "Good evening",
      night: "Good night",
    },
  },
};
